- name: Build fio from source
  hosts: all
  become: true
  vars_files:
    - ceph-build-vars.yml
  tasks:

    - name: Check if fio source directory exists
      ansible.builtin.stat:
        path: "{{ git_base_dir }}/{{ fio_dest_name }}"
      register: fio_dir_stat
      become: false

    - name: Clone fio repository
      ansible.builtin.git:
        repo: "{{ fio_repo_url }}"
        dest: "{{ git_base_dir }}/{{ fio_dest_name }}"
        version: "{{ fio_version }}"
        recursive: yes
      become: false
      when: not fio_dir_stat.stat.exists

    - name: Update fio submodules
      ansible.builtin.command:
        cmd: git submodule update --init --recursive
        chdir: "{{ git_base_dir }}/{{ fio_dest_name }}"
      become: false
      when: not fio_dir_stat.stat.exists

    - name: Configure fio
      ansible.builtin.command:
        argv:
          - ./configure
          - --prefix={{ fio_install_prefix }}
          - --extra-cflags=-I{{ fio_install_prefix }}/include -L{{ fio_install_prefix }}/lib64
        chdir: "{{ git_base_dir }}/{{ fio_dest_name }}"
      become: false
      when: not fio_dir_stat.stat.exists

    - name: Install fio
      ansible.builtin.command:
        cmd: make install
        chdir: "{{ git_base_dir }}/{{ fio_dest_name }}"
      when: not fio_dir_stat.stat.exists
