nodes:
  admin: "root@172.21.13.10"
  servers: ["root@172.21.13.12", "root@172.21.13.13", "root@172.21.13.14"]
  clients: ["root@172.21.13.11"]

fs_name: "perf_test_fs"
num_filesystems: 1
mds_yaml_path: "/cephfs_perf/mds.yaml" # Contains 'service_type: mds' spec

# SpecStorage configuration
#specstorage:
#  prototype: "/cephfs_perf/sfs2020/sfs_rc"
#  output_path: "/cephfs_perf/sfs2020/spec_2020.txt"
#  run_command: "/cephfs_perf/sfs2020/run_sfs2020_workload.py"
#  workload_dir: "/cephfs_perf/sfs2020/SPECstorage2020"
#  results_base_dir: "/cephfs_perf/sfs2020/SPECstorage2020/results"
#  mounts_per_fs: 1
#  perf_record: true
#  perf_record_script: "/cephfs_perf/sfs2020/perf_record.py"
#  perf_record_executable: "ceph-mds"
#  perf_record_duration: 5
#  lockstat:
#    enabled: true
#    path: "/usr/local/bin/ceph-lockstat"
#    threshold: 0

# Fio configuration (Uncomment to use FioWorkloadRunner instead of SpecStorageWorkloadRunner)
#fio:
#  results_base_dir: "/cephfs_perf/fio"
#  run_command: "/cephfs_perf/fio/run_fio_workload.py"
#  perf_record_script: "/cephfs_perf/fio/perf_record.py"
#  perf_record_executable: "ganesha.nfsd"
#  perf_record: true
#  perf_record_duration: 5
#  flamegraph_path: "/cephfs_perf/FlameGraph"
#  stap_script: "/cephfs_perf/fio/rdtsc-para-callgraph-verbose.stp"
#  mounts_per_fs: 1
#  commands:
#    - "fio --name=ibm_01 --directory={mount_point} --size=5G --bs=256k --iodepth=1 --rw=randrw --ioengine=libaio --time_based=1 --runtime=60 -direct=1 --buffered=0 --gtod_reduce=1 --randrepeat=1 --create_serialize=0 --ramp_time=1s --numjobs=8"

# CephFS-Tool configuration
cephfs_tool:
  results_base_dir: "/cephfs_perf/cephfs_tool"
  run_command: "/cephfs_perf/cephfs_tool/run_cephfs_workload.py"
  perf_record_script: "/cephfs_perf/sfs2020/perf_record.py"
  perf_record_executable: "cephfs-tool"
  perf_record: true
  perf_record_duration: 5
  executable_path: "/usr/local/bin/cephfs-tool"
  ceph_args: "--log-to-stderr=false --log-to-file=false --log-file=/tmp/bench.log"
  config_path: "/etc/ceph/ceph.conf"
  keyring: "/etc/ceph/ceph.client.admin.keyring"
  client_id: "admin"
  root_path: "/"
  duration: 15
  loadpoints:
    - files: 1024
      size: "128MiB"
      threads: 32
      iterations: 3
      client-oc: 1
      client-oc-size: "1GiB"
      extra_args: ""

ganesha:
  enabled: false
  service_id: "ganesha"
  type: "systemd"
  binary_path: "/usr/local/bin/ganesha.nfsd"
  pid_path: "/var/run/ganesha.pid"
  config_path: "/etc/ganesha/ganesha.conf"
  worker_threads: 8

logging:
  enabled: false
  debug_mds: 5
  debug_ms: 1

# Ranges for MDS settings (start, stop, step)
mds_settings:
#  max_mds: [1, 2, 1]
  mds_cache_memory_limit: [128Gi]
#  mds_cache_memory_limit: [1Gi, 4Gi, 16Gi, 64Gi, 192Gi]
#  cpus: [1, 2, 3, 4]
#  mds_max_caps_per_client: [100k, 200k, 100k]
#  mds_recall_max_caps: [5k, 10k, 5k]
#  mds_recall_max_decay_rate: [1, 2, 1]
#  mds_cache_trim_threshold: [64Ki, 128Ki, 64Ki]
##  mds_cache_reservation: [5, 10, 5]
##  mds_log_max_segments: [30, 60, 30]
